<a href="https://colab.research.google.com/github/andres-merino/AprendizajeAutomaticoInicial-05-N0105/blob/main/2-Notebooks/06-2-SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table style="border: none; border-collapse: collapse;">
    <tr>
        <td style="width: 20%; vertical-align: middle; padding-right: 10px;">
            <img src="https://i.imgur.com/nt7hloA.png" width="100">
        </td>
        <td style="width: 2px; text-align: center;">
            <font color="#0030A1" size="7">|</font><br>
            <font color="#0030A1" size="7">|</font>
        </td>
        <td>
            <p style="font-variant: small-caps;"><font color="#0030A1" size="5">
                <b>Facultad de Ciencias Exactas, Naturales y Ambientales</b>
            </font> </p>
            <p style="font-variant: small-caps;"><font color="#0030A1" size="4">
                Aprendizaje Automático Inicial &bull; Descomposición en Valores Singulares (SVD)
            </font></p>
            <p style="font-style: oblique;"><font color="#0030A1" size="3">
                Andrés Merino &bull; Periodo 2025-02
            </font></p>
        </td>  
    </tr>
</table>

---
## <font color='264CC7'> Introducción </font>

La descomposición en valores singulares (SVD) es una herramienta del álgebra lineal y tiene varias aplicaciones en aprendizaje automático: reducción de dimensionalidad, compresión, y sistemas de recomendación, entre otros.

Dada una matriz $A\in \mathbb{R}^{m \times n}$, la SVD la descompone en tres matrices:
- $U \in \mathbb{R}^{m \times m}$: matriz ortogonal cuyas columnas son los vectores singulares de la izquierda.
- $\Sigma \in \mathbb{R}^{m \times n}$: matriz diagonal con los valores singulares (ordenados).
- $V^T \in \mathbb{R}^{n \times n}$: matriz ortogonal cuyas filas son los vectores singulares de la derecha.
La descomposición se expresa como:
$$ A = U \Sigma V^T $$

In [1]:
import numpy as np

---
## <font color='264CC7'> Ejemplo: Encontrado de patrones y sistemas de recomendación </font>

Consideremos una matriz de calificaciones de usuarios a películas:
|       | Ali | Beatrix | Chandra| Ricardo | Sol |
|-------|-----|---------|--------|---------|-----|
| Star Wars | 5   | 4       | 1      | 1 | 5 |
| Blade Runner | 5   | 5       | 0      | 1 | 5 |
| Amelie | 0 | 0 | 5 | 1 | 5 |
| Delicatessen | 1 | 0 | 4 | 1 | 5 |
| Harry Potter | 3 | 5 | 1 | 1 | 5 |
| El señor de los anillos | 5 | 1 | 2 | 1 | 5 |

In [7]:
# Matriz
A = np.array([[5, 4, 1, 1, 5],
              [5, 5, 0, 1, 5],
              [0, 0, 5, 1, 5],
              [1, 0, 4, 1, 5],
              [3, 5, 1, 1, 5],
              [5, 1, 2, 1, 5],])

print("Matriz original A:")
print(A)

Matriz original A:
[[5 4 1 1 5]
 [5 5 0 1 5]
 [0 0 5 1 5]
 [1 0 4 1 5]
 [3 5 1 1 5]
 [5 1 2 1 5]]


Apliquemos SVD para encontrar patrones en las preferencias de los usuarios.

In [8]:
# Descomposición SVD
U, S, VT = np.linalg.svd(A, full_matrices=False)
print("\nMatriz U:")
print(U)
print("\nValores singulares (vector S):")
print(S)
print("\nMatriz V^T:")
print(VT)


Matriz U:
[[-4.72756308e-01  2.34202507e-01 -1.13066602e-01  6.22410001e-01
   4.52303239e-01]
 [-4.81288516e-01  3.97354635e-01  8.63158282e-02 -3.20010530e-01
   2.52697286e-01]
 [-2.92437751e-01 -6.77937283e-01  2.58035068e-01  4.26806908e-01
  -1.54820935e-01]
 [-3.06384456e-01 -5.32182413e-01 -3.96949840e-04 -5.49033600e-01
   4.52303239e-01]
 [-4.38103864e-01  1.99693510e-01  5.78474124e-01 -1.37227066e-01
  -5.17554139e-01]
 [-4.16577206e-01 -6.75566496e-02 -7.60625371e-01 -8.81235084e-02
  -4.84928689e-01]]

Valores singulares (vector S):
[1.70241656e+01 7.45771986e+00 3.06930902e+00 3.73553630e-01
 4.98405787e-17]

Matriz V^T:
[[-4.97751631e-01 -4.05574317e-01 -2.60320609e-01 -1.41419448e-01
  -7.07097240e-01]
 [ 3.87102309e-01  5.16846191e-01 -6.99896678e-01 -5.98608827e-02
  -2.99304414e-01]
 [-7.17378175e-01  6.87795841e-01  7.58295485e-02  1.58785238e-02
   7.93926190e-02]
 [ 2.96249338e-01  3.08733492e-01  6.60778102e-01 -1.20940586e-01
  -6.04702931e-01]
 [-0.00000000e+

Los valores singulares nos indican la importancia de cada componente en la reconstrucción de la matriz original. Podemos tomar los dos primeros que son significativamente mayores. Esto nos indica que hay dos patrones principales en las preferencias de los usuarios y de tipos de películas.

En la matriz $U$, el primer vector singular (primera columna) tiene valores absolutos altos para Star Wars y Blade Runner, indicando que este componente representa una preferencia por películas de ciencia ficción. El segundo vector singular (segunda columna) tiene valores altos para Amelie y Delicatessen, sugiriendo una preferencia por películas de arte y drama.

En la matriz $V^T$, el primer vector singular (primera fila) tiene valores altos para Ali y Beatrix, indicando que estos usuarios prefieren películas de ciencia ficción. El segundo vector singular (segunda fila) tiene un valor alto para Chandra, sugiriendo que este usuario prefiere películas de arte y drama.

---

<div style="background-color: #edf1f8; border-color: #264CC7; border-left: 5px solid #264CC7; padding: 0.5em;">
<strong>Ejercicio:</strong><br>
Amplía los datos del ejemplo agregando más usuarios y películas. Luego, implementa la SVD para realizar otra clasificación de conceptos.
</div>

---